---
title: "MARBLES_CORD_ASD"
author: "John Dou"
date: "June 25, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=F, warning=F}
library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(sas7bdat)
library(openxlsx)
 
res.path <- "/dcl01/NDEpi/data/Projects/InProgress/jdou/DNAm_EARLI_MARBLES/MARBLES_cord/"
```

# MARBLES Processing

## Load preprocessed data and covariates

```{r}
pd.cov <- readRDS(file.path(res.path,'QC/pd.rds'))
beta <- readRDS(file.path(res.path,'QC/beta.rds'))

supp <- read.sas7bdat('/dcl01/NDEpi/data/Projects/InProgress/jdou/MARBLES/Placenta_Supp/e_m_vit_supp_20190411.sas7bdat')
```

## Get supplement

```{r}
supp <- supp[match(pd.cov$COI_ID, supp$coi_id),]
pd.cov$PVmo1 <- supp$PV_YN_MO1

```

# model fitting
```{r models}
library(qqman)
library(limma)

### no missing, no smokers

#get rid of smoking
pd.mod <- pd.cov[pd.cov$smk_preg!=1,]

#get rid missing
pd.mod <- pd.mod[,c('COI_ID', 'PVmo1', 'mom_edu_bn', 'pc1', 'pc2', 'pc3', 'pc4', 'pc5',
                    'sex', 'mom_age', 'gest_age', 'CD8T', 'CD4T', 'NK', 'Bcell', 'Mono',
                    'Gran', 'nRBC')]
pd.mod <- na.omit(pd.mod)

nrow(pd.cov) #223
nrow(pd.mod) #201

#put back in vars only for descriptive purposes
pd.mod$ancest_cat <- pd.cov[match(pd.mod$COI_ID, pd.cov$COI_ID),'ancest_cat']
pd.mod$meanDNAm.sea <- pd.cov[match(pd.mod$COI_ID, pd.cov$COI_ID),'meanDNAm.sea']
pd.mod$meanDNAm.shelf <- pd.cov[match(pd.mod$COI_ID, pd.cov$COI_ID),'meanDNAm.shelf']
pd.mod$meanDNAm.shore <- pd.cov[match(pd.mod$COI_ID, pd.cov$COI_ID),'meanDNAm.shore']
pd.mod$meanDNAm.island <- pd.cov[match(pd.mod$COI_ID, pd.cov$COI_ID),'meanDNAm.island']
pd.mod$meanDNAm <- pd.cov[match(pd.mod$COI_ID, pd.cov$COI_ID),'meanDNAm']

pd.mod$CD8T <- pd.mod$CD8T * 100
pd.mod$CD4T <- pd.mod$CD4T * 100
pd.mod$NK <- pd.mod$NK * 100
pd.mod$Bcell <- pd.mod$Bcell * 100
pd.mod$Mono <- pd.mod$Mono * 100
pd.mod$Gran <- pd.mod$Gran * 100
pd.mod$nRBC <- pd.mod$nRBC * 100


### table 1
library(compareGroups)

restab <- compareGroups(PVmo1 ~ mom_edu_bn + ancest_cat + sex +
                          mom_age + gest_age + CD8T + CD4T + NK + Bcell + Mono + Gran + nRBC +
                          meanDNAm + meanDNAm.sea + meanDNAm.shelf + meanDNAm.shore + meanDNAm.island,
                        data=pd.mod, method=c(ancest_cat=3))


tab1 <- createTable(restab)
export2word(tab1, file=file.path(res.path,'PV/table1.docx'))


#### model
mod <- model.matrix(~factor(pd.mod$PVmo1) + pd.mod$sex + pd.mod$mom_age + pd.mod$gest_age + pd.mod$mom_edu_bn + pd.mod$pc1 + pd.mod$pc2 + pd.mod$pc3 + pd.mod$pc4 + pd.mod$pc5 + pd.mod$Gran + pd.mod$nRBC)
out <- lmFit(beta[,rownames(pd.mod)],mod)
out <- eBayes(out)
ss.hits.pv <- topTable(out, coef=2, number=nrow(beta))

lambda <- qchisq(median(ss.hits.pv$P.Value, na.rm=T), df = 1, lower.tail = F) / qchisq(0.5, 1)

png(file.path(res.path,'PV/QQ_pv_mo1.png'))
  qq(ss.hits.pv$P.Value,main=paste0("Lambda = ", round(lambda,3)))
dev.off()

saveRDS(ss.hits.pv, file=file.path(res.path,"PV/model_results_pv_mo1.rds"))


### write table

setwd(file.path(res.path,"PV"))
source("/dcl01/NDEpi/data/Projects/InProgress/jdou/Folate/EARLI_folate_intake_functions.R")

ss.pv <- append.annotate(ss.hits.pv, what=c("chr","pos","gene"), array="EPIC")

nice.format <- function(ss.hits){
  ss.hits$sd <- ss.hits$logFC/ss.hits$t
  ss.hits <- ss.hits[,c("chr","pos","logFC","sd","P.Value","adj.P.Val","gene","AveExpr")]
  names(ss.hits) <- c("chr","pos","DNAm_diff","sd","P.Value","adj.P.Val","gene","AveDNAm")
  ss.hits$DNAm_diff <- signif(ss.hits$DNAm_diff*100,4)
  ss.hits$sd <- signif(ss.hits$sd*100,4)
  ss.hits$P.Value <- signif(ss.hits$P.Value, 3)
  ss.hits$adj.P.Val <- round(ss.hits$adj.P.Val,2)
  ss.hits$AveDNAm <- round(ss.hits$AveDNAm*100,2)
  ss.hits$gene <- gsub(";.*","",ss.hits$gene)
  ss.hits$gene <- paste0(" ", ss.hits$gene)
  ss.hits
}

ss.pv.fmt <- nice.format(ss.pv)

write.csv(ss.pv.fmt, file="Supplementary Table 4 - MARBLES Cord Blood Single Site Results.csv")
```



## single site results visualization
```{r ss visual}
setwd(file.path(res.path,"PV"))
ss.hits.pv <- readRDS("model_results_pv_mo1.rds")


plot.volcano <- function(ss.hits,main=NULL){
  par(mar=c(5,5,3,3))
  
  #get betas and pvals from single sites results
  betas <- ss.hits$logFC
  pvals <- -log(ss.hits$P.Value,10)
  
  #assign colors
  pcol <- ifelse(pvals < -log(0.05,10), 'darkslategrey', ifelse(betas>0,'cadetblue4','cadetblue3'))
  
  #get percent hyper/hypo for sites above threshold
  total <- table(pcol)['cadetblue4'] + table(pcol)['cadetblue3']
  pct <- c(round(table(pcol)['cadetblue4']/total * 100,1),round(table(pcol)['cadetblue3']/total * 100,1))
  
  #plotting stuff
  plot(betas,pvals, las=1, main=main, xlab=paste0('Effect Estimate'), ylab=expression('-Log'[10]*'(P-Value)'),
       xlim=c(-0.46,0.46),ylim=c(0,7),cex.axis=1.4,cex.lab=1.4,cex.main=1.4,cex=0.7,pch=21,col=pcol)
  abline(h=-log(0.05,10),col='blue')
  abline(h=7,col='red')
  text(0.3,6,paste0(pct[1],'%'),col='cadetblue4',cex=2.2)
  text(-0.3,6,paste0(pct[2],'%'),col='cadetblue3',cex=2.2)
}


png("volcano_pv_mo1.png")
  plot.volcano(ss.hits.pv)
dev.off()



### manhattan plots

#append chr and bp info
data(Locations)

ss.hits.pv <- ss.hits.pv[rownames(ss.hits.pv) %in% rownames(Locations), ]

ss.hits.pv$CHR <- Locations[rownames(ss.hits.pv),"chr"]
ss.hits.pv$BP <- Locations[rownames(ss.hits.pv),"pos"]
ss.hits.pv$CHR <- as.numeric(gsub("chr","",ss.hits.pv$CHR))

png("manhattan_pv_mo1.png")
  manhattan(ss.hits.pv, p="P.Value")
dev.off()
```


# pathway analysis
```{r pathway}
library(missMethyl)

setwd(file.path(res.path,"PV"))
ss.hits.pv <- readRDS("model_results_pv_mo1.rds")

table(ss.hits.pv$P.Value<0.01) #4025

top.pv <- rownames(ss.hits.pv[ss.hits.pv$P.Value<0.01, ])

mm.pv <- gometh(sig.cpg=top.pv, all.cpg=rownames(ss.hits.pv), collection="GO", array.type="EPIC")


path.pv <- topGSA(mm.pv, number=nrow(mm.pv))

path.pv <- path.pv[path.pv$ONTOLOGY=='BP',]

write.csv(path.pv, file="pathway_pv_mo1.csv")
```


# global 
```{r global}
globalRegions <- function(pd, x, adj=NULL, summary.name){
  #set up blank results
  regions <- c('meanDNAm','meanDNAm.sea','meanDNAm.shore','meanDNAm.shelf','meanDNAm.island')
  fits <- list()
  fits[regions] <- NA
  results <- matrix(NA, nrow=5, ncol=4)
  rownames(results) <- regions
  colnames(results) <- c('est', 'std_err', 't', 'p')
  
  #do linear model for each region
  for(region in regions){
    eqn <- paste0(region, '~', x, '+', adj)
    fits[[region]] <- lm(as.formula(eqn), data=pd)
    results[region,] <- summary(fits[[region]])$coefficients[2,]
  }
  
  #print out summaries
  sink(paste0(summary.name,'.txt'), append=TRUE)
  print(lapply(fits, summary))
  sink()
  
  return(results)
}

pd.mod$PVmo1 <- factor(pd.mod$PVmo1)

PV_all <- globalRegions(pd.mod, x='PVmo1', adj='sex + mom_age + gest_age + mom_edu_bn + pc1 + pc2 + pc3 + pc4 + pc5 + Gran + nRBC', summary.name='PV_all')

saveRDS(PV_all, file='global_pv_mo1.rds')
```